// GENERATED BY MITOSIS

import { component$, useClientEffect$, useSignal } from '@builder.io/qwik';
export interface PortalProps {
  target: HTMLElement | string;
  children?: any;
}
export const Portal = component$<PortalProps>((props) => {
  const el = useSignal<HTMLElement>();

  useClientEffect$(({ cleanup }) => {
    const target =
      typeof props.target === 'string'
        ? document.querySelector(props.target)
        : props.target;

    target.appendChild(el.value);

    cleanup(() => {
      if (el.value?.parentNode) {
        el.value.parentNode.removeChild(el.value);
      }
    });
  });

  return (
    <div ref={el}>
      <Slot />
    </div>
  );
});
export default Portal;
